### PR TITLE
Change package name

### LINKED ISSUE #412: Evaluate choice in package IDs
All Microsoft internal tools packages should have IDs that begin with `Microsoft.` so that their absence from nuget.org does not present a dependency confusion vulnerability to repos that consume it from one feed and also consume nuget.org via nuget.config.

### PR DESCRIPTION
**Pull request by jonfortescue**
Fixes #412.

### CODE REVIEW

**Review by MattGal — APPROVED** [review]

**Review by riarenas — APPROVED** [review]
Changes look good, just wondering if we want to name it `Microsoft.Dotnet.XliffTasks` but I'm not sure who should make the call on what the official name should be. Maybe @mmitche?

**Comment by mmitche** [comment]
> Changes look good, just wondering if we want to name it `Microsoft.Dotnet.XliffTasks` but I'm not sure who should make the call on what the official name should be. Maybe @mmitche?

No objections from me.

**Comment by riarenas** [comment]
>No objections from me.

So `Microsoft.XliffTasks` is fine?

**Comment by mmitche** [comment]
> > No objections from me.
> 
> So `Microsoft.XliffTasks` is fine?

Hmm. I like `Microsoft.DotNet.XliffTasks` better.

**Review by riarenas — CHANGES_REQUESTED** [review]
Just blocking so we don't forget to change the package name to `Microsoft.Dotnet.XliffTasks` instead.

**Comment by lpatalas** [comment]
@riarenas I have renamed the package to `Microsoft.DotNet.XliffTasks`. Could you take another look?

**Review by riarenas — APPROVED** [review]

**Pull request merged**
