### PR TITLE
Remove sourcelink dependency

### PR DESCRIPTION
**Pull request by NikolaMilosavljevic**
Contributes to https://github.com/dotnet/source-build/issues/3551

Sourcelink dependency isn't needed anymore. Arcade uses sourcelink tooling that is included in .NET SDK 8.0 preview 6.

### CODE REVIEW

**Comment by NikolaMilosavljevic** [comment]
cc @mmitche @dotnet/source-build-internal

**Comment by NikolaMilosavljevic** [comment]
Investigating source-build break - did not repro in local product build.

**Comment by NikolaMilosavljevic** [comment]
This repo will need an Arcade update, to unblock the repo-level source-build.

**Comment by mmitche** [comment]
@NikolaMilosavljevic you might combine these changes with https://github.com/dotnet/xliff-tasks/pull/790#issuecomment-1670174730 (merge the branch in)

**Comment by mmitche** [comment]
Can you merge from the Maestro branch to your branch?

**Pull request merged**
