### PR TITLE
Include xlf as input for incrementality

### LINKED ISSUE #28: Incremental build does not update xlf if only xlf file has changed
We compare source file to up-to-date marker, but not xlf file.

### PR DESCRIPTION
**Pull request by nguerrera**
Fix #28

### CODE REVIEW

**Comment by nguerrera** [comment]
Fix #28 

Draft because this is completely untested so far.

**Comment by tmeschter** [comment]
More than once I've seen an issue where just a `<notes />` element was changed in a .xlf and it no longer matches what is in the .resx. XliffTasks will complain that the .xlf is out-of-date but a regular build won't actually update it. Touching the .resx file and then building again causes it to then be updated. Would this update fix that problem?

**Comment by nguerrera** [comment]
Yes.

**Comment by tmeschter** [comment]
@nguerrera You still have this listed as a draft. What do we need to do to move forward with it?

**Comment by nguerrera** [comment]
I forgot about it. It needs testing. This was just typed in to the browser to capture the idea. I am swamped at the moment.

**Comment by tmeschter** [comment]
I know the feeling. :-(

**Comment by nguerrera** [comment]
Closing this since I won't get back to it. If someone is motivated to fix #28, this might be a good starting point, but it's untested.

**Pull request closed without merging**
